
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Model
{

using System;
    using System.Collections.Generic;
    
public partial class DO_t_TemporaryScan
{

    public string fStOutLogNo { get; set; }

    public string fPackNo { get; set; }

    public string fOrdNo { get; set; }

    public string fBarcode { get; set; }

    public string fGoodsCode { get; set; }

    public string fSizeDesc { get; set; }

    public string saveDate { get; set; }

    public string fGoodsName { get; set; }

}

}
