//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_ADMM_UsrDataRightItem
    {
        public string fUsrType { get; set; }
        public string fUsrID { get; set; }
        public string fItemCode { get; set; }
        public string fApplyScope { get; set; }
        public string fModuleCode { get; set; }
        public int fSNo { get; set; }
        public string fFormCode { get; set; }
        public string fValueType { get; set; }
        public string fValue { get; set; }
        public string fValueDesc { get; set; }
        public string fCreatorID { get; set; }
        public string fCreator { get; set; }
        public Nullable<System.DateTime> fCDate { get; set; }
        public string fModifierID { get; set; }
        public string fModifier { get; set; }
        public Nullable<System.DateTime> fModiDate { get; set; }
        public string fExpCfg { get; set; }
    }
}
