
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Model
{

using System;
    using System.Collections.Generic;
    
public partial class t_ADMM_UsrMst
{

    public string fUsrID { get; set; }

    public string fUsrName { get; set; }

    public string fUsrEName { get; set; }

    public int fLangID { get; set; }

    public byte[] fUsrStamp { get; set; }

    public System.DateTime fEnableDate { get; set; }

    public Nullable<System.DateTime> fDisableDate { get; set; }

    public int fEffectDaysOfPW { get; set; }

    public Nullable<System.DateTime> fDisableDateOfPW { get; set; }

    public string fIfUse { get; set; }

    public string fIfSupper { get; set; }

    public string fDateFormat { get; set; }

    public string fMobile { get; set; }

    public string fEmail { get; set; }

    public string fEmpNo { get; set; }

    public string fRemark { get; set; }

    public string fCFlag { get; set; }

    public string fCreatorID { get; set; }

    public string fCreator { get; set; }

    public Nullable<System.DateTime> fCDate { get; set; }

    public string fModifierID { get; set; }

    public string fModifier { get; set; }

    public Nullable<System.DateTime> fModiDate { get; set; }

    public string fApproverID { get; set; }

    public string fApprover { get; set; }

    public Nullable<System.DateTime> fAppDate { get; set; }

    public short fSharedIndex { get; set; }

    public Nullable<bool> fCanManualNote { get; set; }

    public Nullable<bool> fCanWFNote { get; set; }

    public Nullable<bool> fCanProgNote { get; set; }

    public string fCanLoginPCList { get; set; }

    public string fUsbKey { get; set; }

    public bool fIfEMSUsr { get; set; }

    public string fIfPrv { get; set; }

    public string fPrvCode { get; set; }

    public byte[] fTimeStamp { get; set; }

    public string fLinkNo { get; set; }

    public string fSrcSys { get; set; }

    public string fMainUIType { get; set; }

    public string fUseOnLock { get; set; }

    public string C_x_f009 { get; set; }

    public string C_x_f010 { get; set; }

}

}
