
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Model
{

using System;
    using System.Collections.Generic;
    
public partial class t_BCMM_BarcodeItem
{

    public string fBarcode { get; set; }

    public string fPackNo { get; set; }

    public decimal fPackCtnsByPCS { get; set; }

    public Nullable<int> fSPCode { get; set; }

    public string fCstLotNo { get; set; }

    public string fSPName { get; set; }

    public string fSPSizeDesc { get; set; }

    public string fGoodsOUnit { get; set; }

    public Nullable<decimal> fCtnL { get; set; }

    public Nullable<decimal> fCtnW { get; set; }

    public Nullable<decimal> fCtnH { get; set; }

    public Nullable<decimal> fCubeRate { get; set; }

    public Nullable<decimal> fOutCuft { get; set; }

    public Nullable<decimal> fOutM3 { get; set; }

    public Nullable<decimal> fNetWeight { get; set; }

    public Nullable<decimal> fGrossWeight { get; set; }

    public string fWeightUnitCode { get; set; }

    public int fPrNTimes { get; set; }

    public string fRemark { get; set; }

    public Nullable<System.DateTime> fFirstPrnDate { get; set; }

    public Nullable<System.DateTime> fLastPrnDate { get; set; }

    public string fCreatorID { get; set; }

    public string fCreator { get; set; }

    public Nullable<System.DateTime> fCDate { get; set; }

    public string fModifierID { get; set; }

    public string fModifier { get; set; }

    public Nullable<System.DateTime> fModiDate { get; set; }

    public string fFormerBarcode { get; set; }

    public int fLSNo { get; set; }

    public string fSPNameEn { get; set; }

    public string fSPSizeDescEn { get; set; }

    public byte[] fTimeStamp { get; set; }

    public string fBigBarCode { get; set; }

    public string fFangWeiNo { get; set; }

    public string fZhuiSuNo { get; set; }

    public string fXulieNo { get; set; }

    public int fsubpacksno { get; set; }

}

}
