
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Model
{

using System;
    using System.Collections.Generic;
    
public partial class t_BCMM_BarcodeMst
{

    public string fPackNo { get; set; }

    public string fBarType { get; set; }

    public string fOriType { get; set; }

    public string fMoNo { get; set; }

    public string fPurNo { get; set; }

    public string fOrdNo { get; set; }

    public Nullable<int> fSingleSetSNo { get; set; }

    public Nullable<int> fSetGoodsID { get; set; }

    public string fSetDesc { get; set; }

    public string fIfMix { get; set; }

    public string fWhole { get; set; }

    public decimal fCtnQty { get; set; }

    public string fCreatorID { get; set; }

    public string fCreator { get; set; }

    public Nullable<System.DateTime> fCDate { get; set; }

    public string fModifierID { get; set; }

    public string fModifier { get; set; }

    public Nullable<System.DateTime> fModiDate { get; set; }

    public string fIfCancel { get; set; }

    public string fCancelID { get; set; }

    public string fCanceler { get; set; }

    public Nullable<System.DateTime> fCancelDate { get; set; }

    public Nullable<System.DateTime> fFstInDate { get; set; }

    public decimal fQty { get; set; }

    public string fOriNo { get; set; }

    public string fSaleBindCode { get; set; }

    public byte[] fTimeStamp { get; set; }

    public int fPackSNo { get; set; }

    public Nullable<System.DateTime> fLastTestDate { get; set; }

    public int fTestStatus { get; set; }

    public string fRemark { get; set; }

}

}
