
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Model
{

using System;
    using System.Collections.Generic;
    
public partial class t_BCMM_BarcodeFgItem
{

    public string fPackNo { get; set; }

    public int fGoodsID { get; set; }

    public string fCstLotNo { get; set; }

    public string fGoodsName { get; set; }

    public string fSizeDesc { get; set; }

    public string fUnitCode { get; set; }

    public decimal fQty { get; set; }

    public string fStkOrdNo { get; set; }

    public string fStkMoNo { get; set; }

    public string fLotNo { get; set; }

    public string fCreatorID { get; set; }

    public string fCreator { get; set; }

    public Nullable<System.DateTime> fCDate { get; set; }

    public string fModifierID { get; set; }

    public string fModifier { get; set; }

    public Nullable<System.DateTime> fModiDate { get; set; }

    public int fOrdSNo { get; set; }

    public string fRemark { get; set; }

    public string fEName { get; set; }

    public string fEnSizeDesc { get; set; }

    public string fEnAlias { get; set; }

}

}
