
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Model
{

using System;
    using System.Collections.Generic;
    
public partial class t_CRMM_CstMst
{

    public string fCCode { get; set; }

    public string fCNName { get; set; }

    public string fCName { get; set; }

    public string fQuickQuery { get; set; }

    public string fCountryCode { get; set; }

    public string fZoneCode { get; set; }

    public string fChannelCode { get; set; }

    public string fAddress { get; set; }

    public string fTel { get; set; }

    public string fFax { get; set; }

    public string fEmail { get; set; }

    public string fPostCode { get; set; }

    public string fHttp { get; set; }

    public string fRemark { get; set; }

    public string fIfTrade { get; set; }

    public string fCryCode { get; set; }

    public string fShopCard { get; set; }

    public string fTaxRegNO { get; set; }

    public string fOrganNo { get; set; }

    public string fGathComCode { get; set; }

    public string fPComCode { get; set; }

    public string fOBankCode { get; set; }

    public string fCBank { get; set; }

    public string fCAccount { get; set; }

    public string fCSwiftCode { get; set; }

    public string fTaxType { get; set; }

    public string fTaxCode { get; set; }

    public Nullable<int> fAccountDate { get; set; }

    public Nullable<decimal> fArea { get; set; }

    public string fStkCode { get; set; }

    public string fcFlag { get; set; }

    public string fPayCode { get; set; }

    public string fPriceCode { get; set; }

    public string fTrafficCode { get; set; }

    public decimal fRebate { get; set; }

    public string fProdReq { get; set; }

    public string fIfUse { get; set; }

    public Nullable<int> fDeptId { get; set; }

    public string fSalesManID { get; set; }

    public string fSalesMan { get; set; }

    public string fFollowManID { get; set; }

    public string fFollowMan { get; set; }

    public string fMngLevel { get; set; }

    public string fCstLvlCode { get; set; }

    public string fIfRebates { get; set; }

    public string fRebateSchemeCode { get; set; }

    public string fCreatorID { get; set; }

    public string fCreator { get; set; }

    public Nullable<System.DateTime> fCDate { get; set; }

    public string fModifierID { get; set; }

    public string fModifier { get; set; }

    public Nullable<System.DateTime> fModiDate { get; set; }

    public string fApproverID { get; set; }

    public string fApprover { get; set; }

    public Nullable<System.DateTime> fAppDate { get; set; }

    public int fAttachment { get; set; }

    public short fSharedIndex { get; set; }

    public byte[] fTimeStamp { get; set; }

    public string fIfDlvAmtPublicAutoOrd { get; set; }

    public string fOtrPrv { get; set; }

    public string fUseStatus { get; set; }

    public string fStUseDate { get; set; }

    public string fIntentionGoods { get; set; }

    public Nullable<int> fSaveDays { get; set; }

    public Nullable<System.DateTime> fSaveEndDate { get; set; }

    public string fOriTypeCode { get; set; }

    public string fOriProvider { get; set; }

    public string fCstStatus { get; set; }

    public string fOrganization { get; set; }

    public string fDecisionPrc { get; set; }

    public string fMarketingPloy { get; set; }

    public string fConditionFlag { get; set; }

    public string fLogisticsMode { get; set; }

    public string fIfEBS { get; set; }

    public Nullable<System.DateTime> fTurnDate { get; set; }

    public string fSchemeCode { get; set; }

    public decimal fDepositVal { get; set; }

    public Nullable<System.DateTime> fDepositExpirDate { get; set; }

    public string fProvinceCode { get; set; }

    public string fCityCode { get; set; }

    public decimal fCreditAmtVal { get; set; }

    public decimal fTempCreditAmt { get; set; }

    public Nullable<System.DateTime> fTempCreditExpireDate { get; set; }

    public string fCustSortCode { get; set; }

    public string fDCWFSimplelog { get; set; }

    public string fDistrictCode { get; set; }

    public string fIfIncludeKit { get; set; }

    public string fIfIncludeBrand { get; set; }

    public string fIfLockamt { get; set; }

    public string fChkRFIDType { get; set; }

    public Nullable<decimal> fDeposit { get; set; }

    public Nullable<decimal> fCreditAmt { get; set; }

    public string fifAssignNetOrd { get; set; }

    public string fCustRole { get; set; }

    public string fCoopType { get; set; }

    public string fRegisteraDate { get; set; }

    public decimal fRegisteraAmt { get; set; }

    public int fEmpNum { get; set; }

    public decimal fYProdValue { get; set; }

    public string fMaster { get; set; }

    public string fStoreType { get; set; }

    public string fROSchemeCode { get; set; }

    public Nullable<decimal> fCusPriceRate { get; set; }

    public string C_x_f004 { get; set; }

    public int fDryLeadTime { get; set; }

    public string fIfCanEditPrice { get; set; }

    public string fStep { get; set; }

    public string fSmallStep { get; set; }

}

}
