//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_INVD_StkOutLogMst
    {
        public string fStkOutLogNo { get; set; }
        public string fOriReceiptCode { get; set; }
        public string fOriNo { get; set; }
        public string fMKCode { get; set; }
        public string fStkCode { get; set; }
        public Nullable<int> fDeptID { get; set; }
        public string fEmp { get; set; }
        public System.DateTime fPlanOutDate { get; set; }
        public Nullable<System.DateTime> fActOutDate { get; set; }
        public string fReasonCode { get; set; }
        public Nullable<System.DateTime> fCtnDate { get; set; }
        public string fCtnCode { get; set; }
        public string fCtnNo { get; set; }
        public string fSealNo { get; set; }
        public string fRemark { get; set; }
        public string fIfNeedScan { get; set; }
        public string fScanFlag { get; set; }
        public Nullable<System.DateTime> fScanDate { get; set; }
        public string fScannerID { get; set; }
        public string fScanner { get; set; }
        public string fIfAc { get; set; }
        public string fIfPost { get; set; }
        public string fCreatorID { get; set; }
        public string fCreator { get; set; }
        public Nullable<System.DateTime> fCDate { get; set; }
        public string fModifierID { get; set; }
        public string fModifier { get; set; }
        public Nullable<System.DateTime> fModiDate { get; set; }
        public string fPosterID { get; set; }
        public string fPoster { get; set; }
        public Nullable<System.DateTime> fPostDate { get; set; }
        public string fIfCancel { get; set; }
        public string fCancelID { get; set; }
        public string fCanceler { get; set; }
        public Nullable<System.DateTime> fCancelDate { get; set; }
        public int fAttachment { get; set; }
        public short fSharedIndex { get; set; }
        public string C_CfOutCheck { get; set; }
        public string fAccountantFlag { get; set; }
        public string fAccountantID { get; set; }
        public string fAccountant { get; set; }
        public Nullable<System.DateTime> fAccountantDate { get; set; }
        public string fPrepFlag { get; set; }
        public string fPrvCode { get; set; }
        public string fStkInOutType { get; set; }
        public string fOriReasonCode { get; set; }
        public string fDrvReceiptCode { get; set; }
        public byte[] fTimeStamp { get; set; }
        public string fOriStkOutInLog { get; set; }
        public long fPostSNo { get; set; }
        public string fIfSync { get; set; }
        public string fOutCheckerID { get; set; }
        public string fOutChecker { get; set; }
        public Nullable<System.DateTime> fOutCheckDate { get; set; }
        public string C_x_f004 { get; set; }
        public string C_x_f005 { get; set; }
        public string C_x_f006 { get; set; }
    }
}
