
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Model
{

using System;
    using System.Collections.Generic;
    
public partial class t_INVD_StkOutLogItem
{

    public string fStkOutLogNo { get; set; }

    public int fSNo { get; set; }

    public int fOriSNo { get; set; }

    public string fMoNo { get; set; }

    public string fOrdNo { get; set; }

    public string fStkMoNo { get; set; }

    public string fStkOrdNo { get; set; }

    public int fGoodsID { get; set; }

    public string fGoodsName { get; set; }

    public string fSizeDesc { get; set; }

    public string fUnitCode { get; set; }

    public string fLotNo { get; set; }

    public string fLvlCode { get; set; }

    public string fPlaceCode { get; set; }

    public string fPrvCode { get; set; }

    public decimal fPlanOutQty { get; set; }

    public decimal fActOutQty { get; set; }

    public Nullable<decimal> fCtns { get; set; }

    public decimal fUp { get; set; }

    public decimal fAmt { get; set; }

    public decimal fOUP { get; set; }

    public decimal fOAmt { get; set; }

    public decimal fRmUp { get; set; }

    public decimal fRmAmt { get; set; }

    public decimal fPUP { get; set; }

    public decimal fPAmt { get; set; }

    public decimal fMUP { get; set; }

    public decimal fMAmt { get; set; }

    public string fRemark { get; set; }

    public string fCreatorID { get; set; }

    public string fCreator { get; set; }

    public Nullable<System.DateTime> fCDate { get; set; }

    public string fModifierID { get; set; }

    public string fModifier { get; set; }

    public Nullable<System.DateTime> fModiDate { get; set; }

    public int fAttachment { get; set; }

    public Nullable<int> fDCShowSeqNo { get; set; }

    public string fCstLotNo { get; set; }

    public Nullable<int> fVouID { get; set; }

    public Nullable<int> fVTypeID { get; set; }

    public Nullable<int> fVouNo { get; set; }

    public string fVouGNo { get; set; }

    public string fDlvType { get; set; }

    public string fIfEnableEdit { get; set; }

    public decimal fOriPlanOutQty { get; set; }

    public Nullable<System.DateTime> fCstCalcDate { get; set; }

    public string fCstCalcID { get; set; }

    public string fCstCalcer { get; set; }

    public string fRemark2 { get; set; }

    public string fIfGenVou { get; set; }

    public string fIfInv { get; set; }

    public int fOrdSNo { get; set; }

    public string fSaleBindCode { get; set; }

    public string fBuildingNo { get; set; }

    public string fFloorNo { get; set; }

    public string fArea { get; set; }

    public string fRoomType { get; set; }

    public string fHouseNumber { get; set; }

    public string fGraphNumber { get; set; }

    public string fIfIst { get; set; }

    public string fPrjNo { get; set; }

    public decimal fScanedQty { get; set; }

    public string fTrdNo { get; set; }

    public Nullable<int> fTrdSNo { get; set; }

    public Nullable<int> fTrdVouID { get; set; }

    public Nullable<int> fTrdVTypeID { get; set; }

    public Nullable<int> fTrdVouNo { get; set; }

    public string fTrdVouGNo { get; set; }

    public string fIfGenTrdVou { get; set; }

    public Nullable<int> fTrdVouID2 { get; set; }

    public Nullable<int> fTrdVTypeID2 { get; set; }

    public Nullable<int> fTrdVouNo2 { get; set; }

    public string fTrdVouGNo2 { get; set; }

    public string fIfGenTrdVou2 { get; set; }

    public decimal fSelectedQty { get; set; }

    public string fLinkServer { get; set; }

    public string fLinkDatabase { get; set; }

    public int fTurnAcSubId { get; set; }

    public decimal fActOutQtyOri { get; set; }

    public decimal fDGStkInQty { get; set; }

    public Nullable<System.DateTime> fDGStkInDate { get; set; }

    public string fDGStkInUsrName { get; set; }

}

}
