
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Model
{

using System;
    using System.Collections.Generic;
    
public partial class V_INVD_StkOutLogItemSum
{

    public int fGoodsID { get; set; }

    public string fGoodsCode { get; set; }

    public string fGoodsName { get; set; }

    public string fSizeDesc { get; set; }

    public string fCstLotNo { get; set; }

    public string fGoodsType { get; set; }

    public string fStkOutLogNo { get; set; }

    public string fUnitName { get; set; }

    public Nullable<decimal> fUp { get; set; }

    public Nullable<decimal> fPlanOutQty { get; set; }

    public Nullable<decimal> fActOutQty { get; set; }

    public Nullable<decimal> fplanoutamt { get; set; }

    public Nullable<decimal> fAmt { get; set; }

    public Nullable<decimal> fCtns { get; set; }

    public string fRmQLTName { get; set; }

    public string fClrName { get; set; }

    public string fStyleName { get; set; }

}

}
